name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.3, 8.2, 8.1]
        phpunit: [9.6, 10.0, 11.0]
        dependency-version: [prefer-stable]
        exclude:
          - php: 8.1
            phpunit: 11.0

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: ${{ matrix.phpunit }}
          php_version: ${{ matrix.php }}
